# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1b41170197139025bfa969b6d3f0b74b837d5bed61615fcfacf660d57fb9a0ff34781d773e15440828329bc77cf9f2d6a8ce2bf85b1f9e52371986f74342e34d

test:
  secret_key_base: f9124a91e2ec3cdfb0142b4ece72386e8c6ed5f74dde6592452d108c1d8783527ee8265c44ad32822659cc30b2cc0a8fedfa91ad6f861b485ea11a110b1279c6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
